trigger:
  branches:
    include:
      - new_branch

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
- script: 
    python36 Training2022/Flask/app.py