trigger:
  branches:
    include:
      - new_branch

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: Training2022
    type: github
    endpoint: git@github.com:shaked123456/Training2022.git
    name: shaked123456/Training2022
    ref: new_branch

variables:
 pythonVersion: '3.7'

stages:

 - stage: Build
   displayName: Build stage

   jobs:
   - job: BuildJob

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - script: 
        python Flask/app.py