schedules:
- cron: "3 15 * * *"
  displayName: test-build
  branches:
    include:
    - new_branch

pool:
  vmImage: ubuntu-latest

stages:

- stage: Build
  displayName: Build stage

  jobs:
   - job: Build

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - task: DockerCompose@0
       displayName: Build services
       inputs:
         action: Build services
         dockerComposeFile: docker-compose.yml