trigger:
  branches:
    include:
      - new_branch

pool:
  vmImage: ubuntu-latest

resources:
  repositories:

variables:
 pythonVersion: '3.7'

stages:

 - stage: Build
   displayName: Build stage
   
   jobs:
   - job: BuildJob

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - script: 
        python shaked123456/Training2022/Flask/app.py