# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- new_branch

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: docker build -t flask_app Flask/

- stage: Run
  displayName: Run FlaskApp with the custom image
  jobs:
  - job: Run
    displayName: Run
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: docker run -d flask_app 

  
   

