trigger: none

pool:
  vmImage: ubuntu-latest

schedules:
  - cron: "*/2 * * * *"
    displayName: Run every 2 minutes
    branches:
      include:
        - new_branch
    always: true
    
  - cron: "*/17 * * * *"
    displayName: Run at midnight
    branches:
      include:
        - new_branch
    always: true

stages:

- stage: Build
  displayName: Build stage

  jobs:
   - job: Build

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - task: DockerCompose@0
       displayName: Build services
       inputs:
         action: Build services
         dockerComposeFile: docker-compose.yml