# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- new_branch

resources:
- repo: self

stages:
#- stage: Build
#  displayName: Build image
#  jobs:
#  - job: Build
#    displayName: Build
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - script: docker build -t flask_app Flask/

- stage: Build and Run
  displayName: Build and Run FlaskApp 
  jobs:
  - job: Build_and_Run
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: "docker build -t flask_app Flask/ && docker run -d flask_app"

- stage: Test
  displayName: Testing FlaskApp
  jobs:
  - job: Test
    displayName: Test
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: pytest Flask/test.py 

  
   

