trigger:
  branches:
    include:
      - new_branch

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: Training2022
      type: github

steps:
- script: 
    python Flask/app.py
