trigger:
  branches:
    include:
      - new_branch

pool:
  vmImage: ubuntu-latest

variables:
 pythonVersion: '3.7'

stages:

- stage: Checkout
  displayName: Checkout stage
  
  jobs:
  - job: Build
    steps:
    - checkout: none
    - script: | 
        git clean -ffdx
        git clone  https://$(user):$(pass)@github.com/shaked123456/Training2022.git


- stage: Build
  displayName: Build stage

  jobs:
   - job: Build

     steps:
     - task: UsePythonVersion@0
       inputs:
        versionSpec: '$(pythonVersion)'
       displayName: 'Use Python $(pythonVersion)'

     - script: 
        pip install -r Flask/requirements.txt

     - script: 
        python Flask/app.py